version: "3.8"

services:
  web:
    build: 
      context: ./app
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/usr/src/app
    ports:
      - 8000:8000
    env_file: ./.env.dev
    depends_on:
      - db
      - node
  node:
    build: 
      context: ./app
      dockerfile: Dockerfile.node
    volumes:
      - ./app/bundles-src:/usr/src/app/bundles-src
      - ./app/bundles:/usr/src/app/bundles
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: ./.env.dev.db

volumes:
  postgres_data: