# Generated by Django 3.2 on 2022-05-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_auto_20220515_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_items',
            field=models.ManyToManyField(related_name='items', through='foodcartapp.OrderProduct', to='foodcartapp.Product', verbose_name='Позиция в заказе'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=500, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.CharField(max_length=100, verbose_name='адрес'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='contact_phone',
            field=models.CharField(max_length=50, verbose_name='контактный телефон'),
        ),
    ]
