# Generated by Django 3.2 on 2022-05-27 14:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_auto_20220516_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='price_fixed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена на момент заказа'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_items',
            field=models.ManyToManyField(related_name='orders', through='foodcartapp.OrderProduct', to='foodcartapp.Product', verbose_name='Позиция в заказе'),
        ),
    ]
