# Generated by Django 3.2 on 2022-05-27 14:40

from django.db import migrations


def copy_prices_from_catalogue(apps, schema_editor):
    OrderProduct = apps.get_model('foodcartapp', 'OrderProduct')
    Product = apps.get_model('foodcartapp', 'Product')
    orders = OrderProduct.objects.all()
    for ordered_product in orders.iterator():
        product = Product.objects.get(pk=ordered_product.product.id)
        ordered_product.price_fixed = product.price
        ordered_product.save()


def move_backward(apps, schema_editor):
    OrderProduct = apps.get_model('foodcartapp', 'OrderProduct')
    orders = OrderProduct.objects.all()
    for ordered_product in orders.iterator():
        ordered_product.price_fixed = 0
        ordered_product.save()

class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_auto_20220527_1738'),
    ]

    operations = [
        migrations.RunPython(copy_prices_from_catalogue, move_backward),
    ]
