# Generated by Django 3.2 on 2022-05-28 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_auto_20220527_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'Необработанный'), ('IN_DELIVERY', 'Доставляется'), ('FINISHED', 'Завершен'), ('CANCELED', 'Отменен')], db_index=True, default='NEW', max_length=150, verbose_name='Статус заказа'),
        ),
    ]
