# Generated by Django 3.2 on 2022-05-30 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_auto_20220529_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('SPECIFY', 'Уточнить'), ('CASH', 'Наличные'), ('CARD_ONLINE', 'Картой онлайн'), ('CARD_DELIVERY', 'Картой при получении'), ('CRYPTO', 'Криптовалютой')], db_index=True, default='SPECIFY', max_length=200, verbose_name='Способ оплаты'),
        ),
    ]
